# Workflow - build, publish jar and image to GitHub Packages for this repository(msa-rms-service-user)
name: deploy-workflow

on:
  workflow_dispatch:
    branches: [ main ]

jobs:
  execute:
    uses: extact-io/msa-rms-parent/.github/workflows/deploy-job.yml@main
    with:
      repo: ${{ github.repository }}
      with-image: true
    secrets: inherit
